### ISSUE TITLE
accent normalisation found some other potential issues

### ISSUE THREAD

**Issue by jtauber** [seumasjeltzz/DigitalNyssa#4]
These tokens failed my heuristics for accentuation. Are they incorrectly OCR'd, verbatim mistakes I'll just special case, or something wrong with my heuristics?

ἠ
ὀ
οἰ
το
Ὠς
Δια
κατα
διαδοχοι
ἀλληλοις

**Comment by seumasjeltzz** [comment]
incorrectly OCRd, I'm correcting...

**Comment by seumasjeltzz** [comment]
All fixed.

**Comment by jtauber** [comment]
There still seems to be a ἠ

**Comment by seumasjeltzz** [comment]
I think I got them all.
