### ISSUE TITLE
more breathing issues

### ISSUE THREAD

**Issue by jtauber** [seumasjeltzz/DigitalNyssa#5]
Added another heuristic around breathing and found these:

ὲγὼ
ὴ
ὲᾷν
ὲτιθήνατο
ὴ
ὲμμιχθεῖσα
ὲκεῖνον
ὸ
ὲν
ὲκκαλύπτεταί
ὲσαγηνεύθησαν
ὲν
απράκτους
άνθρωπίνης
ὲπῄειμεν

**Comment by seumasjeltzz** [comment]
disheartening that so many slipped through.

I'll take a pass at them and tidy them up.

**Comment by jtauber** [comment]
oh, and εὶς

**Comment by jtauber** [comment]
What's nice, though, is that now I have these heuristics coded, we can help "spell check" the OCR better (here and beyond). 

I think this is a great end-to-end project!

**Comment by jtauber** [comment]
Two more (that should be it)

αί
οῦν

**Comment by seumasjeltzz** [comment]
edited in the compiled paragraphs, and continuous text version.

**Comment by jtauber** [comment]
Still hitting these:

ὴ (x2)
εὶς
εν
οῦν

**Comment by seumasjeltzz** [comment]
I've made another pass and should have got these.

**Comment by jtauber** [comment]
Yep, my script no longer complains :-)
